name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
    - name: check-trailing-spaces
      uses: marcopaganini/check-trailing-spaces@v1.0.0
    - name: Check Spelling (JS, Vue, HTML, Markdown, Text)
      # You may pin to the exact commit or the version.
      # uses: UnicornGlobal/spellcheck-github-actions@729ccf160f6e72bd078904cddd5e6244f81ee156
      uses: UnicornGlobal/spellcheck-github-actions@0.4.0
